#%RAML 0.8
title: Sjp - Command API
version: v1
protocols: [ HTTP ]

baseUri: http://localhost:8080/sjp-command-api/command/api/rest/sjp

/cases:
  post:
    description: |
      Create a case
      ...
      (mapping):
          requestType: application/vnd.sjp.create-sjp-case+json
          name: sjp.create-sjp-case
      ...
    body:
      application/vnd.sjp.create-sjp-case+json:
        example:
          !include json/sjp.create-sjp-case.json
        schema:
          !include json/schema/sjp.create-sjp-case.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}/financial-means:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
    defendantId:
      description: The ID of the defendant
      type: string
  post:
    description: |
      Update financial means
      ...
      (mapping):
          requestType: application/vnd.sjp.update-financial-means+json
          name: sjp.update-financial-means
      (mapping):
          requestType: application/vnd.sjp.delete-financial-means+json
          name: sjp.delete-financial-means
      ...
    body:
      application/vnd.sjp.update-financial-means+json:
        example:
          !include json/sjp.update-financial-means.json
        schema:
          !include json/schema/sjp.update-financial-means.json
      application/vnd.sjp.delete-financial-means+json:
        example:
          !include json/sjp.delete-financial-means.json
        schema:
          !include json/schema/sjp.delete-financial-means.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}/all-financial-means:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
    defendantId:
      description: The ID of the defendant
      type: string
  post:
    description: |
      Update all financial means
      ...
      (mapping):
          requestType: application/vnd.sjp.update-all-financial-means+json
          name: sjp.update-all-financial-means
      ...
    body:
      application/vnd.sjp.update-all-financial-means+json:
        example:
          !include json/sjp.update-all-financial-means.json
        schema:
          !include json/schema/sjp.update-all-financial-means.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
    defendantId:
      description: The ID of the defendant
      type: string
  post:
    description: |
      Update defendant's personal details or interpreter
      ...
      (mapping):
          requestType: application/vnd.sjp.update-defendant-details+json
          name: sjp.update-defendant-details
      (mapping):
          requestType: application/vnd.sjp.acknowledge-defendant-details-updates+json
          name: sjp.acknowledge-defendant-details-updates
      (mapping):
          requestType: application/vnd.sjp.accept-pending-defendant-changes+json
          name: sjp.accept-pending-defendant-changes
      (mapping):
          requestType: application/vnd.sjp.reject-pending-defendant-changes+json
          name: sjp.reject-pending-defendant-changes
      ...
    body:
      application/vnd.sjp.update-defendant-details+json:
        example:
          !include json/sjp.update-defendant-details.json
        schema:
          !include json/schema/sjp.update-defendant-details.json
      application/vnd.sjp.acknowledge-defendant-details-updates+json: !!null

      application/vnd.sjp.accept-pending-defendant-changes+json:
        example:
          !include json/sjp.accept-pending-defendant-changes.json
        schema:
          !include json/schema/sjp.accept-pending-defendant-changes.json

      application/vnd.sjp.reject-pending-defendant-changes+json:
        example:
          !include json/sjp.reject-pending-defendant-changes.json
        schema:
          !include json/schema/sjp.reject-pending-defendant-changes.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}/nationalInsuranceNumber:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
    defendantId:
      description: The ID of the defendant
      type: string
  post:
    description: |
      Update defendant's national insurance number
      ...
      (mapping):
          requestType: application/vnd.sjp.update-defendant-national-insurance-number+json
          name: sjp.update-defendant-national-insurance-number
      ...
    body:
      application/vnd.sjp.update-defendant-national-insurance-number+json:
        example:
          !include json/sjp.update-defendant-national-insurance-number.json
        schema:
          !include json/schema/sjp.update-defendant-national-insurance-number.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendants/{defendantId}:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
    defendantId:
      description: The ID of the defendant
      type: string
  post:
    description: |
      Update defendant's hearing requirements
      ...
      (mapping):
          requestType: application/vnd.sjp.update-hearing-requirements+json
          name: sjp.update-hearing-requirements
      ...
    body:
      application/vnd.sjp.update-hearing-requirements+json:
        example:
          !include json/sjp.update-hearing-requirements.json
        schema:
          !include json/schema/sjp.update-hearing-requirements.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}/employer:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
    defendantId:
      description: The ID of the defendant
      type: string
  post:
    description: |
      Update or delete employer
      ...
      (mapping):
          requestType: application/vnd.sjp.update-employer+json
          name: sjp.update-employer
      (mapping):
          requestType: application/vnd.sjp.delete-employer+json
          name: sjp.delete-employer
      ...
    body:
      application/vnd.sjp.update-employer+json:
        example:
          !include json/sjp.update-employer.json
        schema:
          !include json/schema/sjp.update-employer.json
      application/vnd.sjp.delete-employer+json: !!null
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendants/{defendantId}/plead-online:
  uriParameters:
    caseId:
      description: The ID of the case update
      type: string
    defendantId:
          description: The ID of the defendant
          type: string
  post:
    description: |
      Receive an online plea
      ...
      (mapping):
          requestType: application/vnd.sjp.plead-online+json
          name: sjp.plead-online
      (mapping):
          requestType: application/vnd.sjp.plead-aocp-online+json
          name: sjp.plead-aocp-online
      ...
    body:
      application/vnd.sjp.plead-online+json:
        example:
          !include json/sjp.plead-online.json
        schema:
          !include json/schema/sjp.plead-online.json

      application/vnd.sjp.plead-aocp-online+json:
        example:
          !include json/sjp.plead-aocp-online.json
        schema:
          !include json/schema/sjp.plead-aocp-online.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/defendants/{defendantId}/plead-online-pcq-visited:
  uriParameters:
    caseId:
      description: The ID of the case update
      type: string
    defendantId:
          description: The ID of the defendant
          type: string
  post:
    description: |
      Receive an online plea for pcq visited
      ...
      (mapping):
          requestType: application/vnd.sjp.plead-online-pcq-visited+json
          name: sjp.plead-online-pcq-visited
      ...
    body:
      application/vnd.sjp.plead-online-pcq-visited+json:
        example:
          !include json/sjp.plead-online-pcq-visited.json
        schema:
          !include json/schema/sjp.plead-online-pcq-visited.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/upload-case-document/{caseDocumentType}:
  uriParameters:
    caseId:
      description: The ID of a case to modify
      type: string
    caseDocumentType:
      description: Type of a document
      type: string
  post:
    description: |
      Upload a case document for a case
      ...
      (mapping):
          requestType: multipart/form-data
          name: sjp.upload-case-document
      (mapping):
          requestType: application/vnd.sjp.upload-case-document+json
          name: sjp.upload-case-document
      ...
    body:
      application/vnd.sjp.upload-case-document+json:
        example:
          !include json/sjp.upload-case-document.json
        schema:
          !include json/schema/sjp.upload-case-document.json
      multipart/form-data:
        formParameters:
          caseDocument:
            description: a case document to be uploaded
            type: file
    responses:
      202:
        description: Accepted
      500:
        description: Internal Server Error

/cases/{caseId}/case-documents:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
  post:
    description: |
      Add a case document to a case
      ...
      (mapping):
          requestType: application/vnd.sjp.add-case-document+json
          name: sjp.add-case-document
      (mapping):
          requestType: multipart/form-data
          name: sjp.upload-case-documents
      ...
    body:
      application/vnd.sjp.add-case-document+json:
        example:
          !include json/sjp.add-case-document.json
        schema:
          !include json/schema/sjp.add-case-document.json
      multipart/form-data:
        formParameters:
          pleaDocument:
            description: Scanned plea document
            type: file
    responses:
      202:
        description: Accepted
      500:
        description: Internal Server Error

/cases/{caseId}/mark-reopened-in-libra:
  uriParameters:
    caseId:
      description: The ID of the case
      type: string
  post:
    description: |
      Mark case as reopened in Libra on this date
      ...
      (mapping):
          requestType: application/vnd.sjp.mark-case-reopened-in-libra+json
          name: sjp.mark-case-reopened-in-libra
      ...
    body:
      application/vnd.sjp.mark-case-reopened-in-libra+json:
        example:
          !include json/sjp.case-reopened-in-libra.json
        schema:
          !include json/schema/sjp.mark-case-reopened-in-libra.json
    responses:
      202:
        description: Accepted

/cases/{caseId}/update-reopened-in-libra:
  uriParameters:
    caseId:
      description: The ID of the case
      type: string
  post:
    description: |
      Update details of a case reopened in Libra
      ...
      (mapping):
          requestType: application/vnd.sjp.update-case-reopened-in-libra+json
          name: sjp.update-case-reopened-in-libra
      ...
    body:
      application/vnd.sjp.update-case-reopened-in-libra+json:
        example:
          !include json/sjp.case-reopened-in-libra.json
        schema:
          !include json/schema/sjp.update-case-reopened-in-libra.json
    responses:
      202:
        description: Accepted

/cases/{caseId}/undo-reopened-in-libra:
  uriParameters:
    caseId:
      description: The ID of the case
      type: string
  post:
    description: |
      Remove details of a case reopened in Libra
      ...
      (mapping):
          requestType: application/vnd.sjp.undo-case-reopened-in-libra+json
          name: sjp.undo-case-reopened-in-libra
      ...
    body:
      application/vnd.sjp.undo-case-reopened-in-libra+json:
        example:
          !include json/sjp.undo-case-reopened-in-libra.json
        schema:
          !include json/schema/sjp.undo-case-reopened-in-libra.json
    responses:
      202:
        description: Accepted

/cases/{caseId}:
  post:
    description: |
      Assigning a case to a user
      ...
      (mapping):
          requestType: application/vnd.sjp.assign-case+json
          name: sjp.assign-case
      (mapping):
          requestType: application/vnd.sjp.resubmit-results+json
          name: sjp.resubmit-results
      (mapping):
          requestType: application/vnd.sjp.resolve-conviction-court-bdf+json
          name: sjp.resolve-conviction-court-bdf
      (mapping):
          requestType: application/vnd.sjp.mark-as-legal-soc-checked+json
          name: sjp.mark-as-legal-soc-checked
      (mapping):
          requestType: application/vnd.sjp.update-offence-code+json
          name: sjp.update-offence-code
      ...
    body:
      application/vnd.sjp.assign-case+json:
        example:
          !include json/sjp.assign-case.json
        schema:
          !include json/schema/sjp.assign-case.json
      application/vnd.sjp.resubmit-results+json:
        schema:
           !include json/schema/sjp.resubmit-results.json
      application/vnd.sjp.resolve-conviction-court-bdf+json: !!null
      application/vnd.sjp.mark-as-legal-soc-checked+json: !!null
      application/vnd.sjp.update-offence-code+json:
        example:
          !include json/sjp.update-offence-code.json
        schema:
          !include json/schema/sjp.update-offence-code.json

    responses:
      202:
        description: Accepted

/cases/{caseId}/unassign:
  post:
    description: |
      Unassigning cases from a user
      ...
      (mapping):
          requestType: application/vnd.sjp.unassign-case+json
          name: sjp.unassign-case
      ...
    body:
      application/vnd.sjp.unassign-case+json: !!null
    responses:
      202:
        description: Accepted

/sessions/{sessionId}:
  post:
    description: |
      Sjp session related commands
      ...
      (mapping):
          requestType: application/vnd.sjp.start-session+json
          name: sjp.start-session
      (mapping):
          requestType: application/vnd.sjp.end-session+json
          name: sjp.end-session
      (mapping):
          requestType: application/vnd.sjp.assign-next-case+json
          name: sjp.assign-next-case
      (mapping):
          requestType: application/vnd.sjp.update-session-bdf+json
          name: sjp.update-session-bdf
      ...
    body:
      application/vnd.sjp.start-session+json:
        example:
          !include json/sjp.start-session.json
        schema:
          !include json/schema/sjp.start-session.json
      application/vnd.sjp.end-session+json: !!null
      application/vnd.sjp.assign-next-case+json: !!null
      application/vnd.sjp.update-session-bdf+json:
        example:
          !include json/sjp.update-session-bdf.json
        schema:
          !include json/schema/sjp.update-session-bdf.json
    responses:
      202:
        description: Accepted

/reset-aocp-session:
  post:
    description: |
      Reset aocp session
      ...
      (mapping):
          requestType: application/vnd.sjp.reset-aocp-session+json
          name: sjp.reset-aocp-session
      ...
    body:
      application/vnd.sjp.reset-aocp-session+json: !!null
    responses:
      202:
        description: Accepted

/cases/{caseId}/dates-to-avoid:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
  post:
    description: |
      Add dates-to-avoid
      ...
      (mapping):
          requestType: application/vnd.sjp.add-dates-to-avoid+json
          name: sjp.add-dates-to-avoid
      ...
    body:
          application/vnd.sjp.add-dates-to-avoid+json:
            example:
              !include json/sjp.add-dates-to-avoid.json
            schema:
              !include json/schema/sjp.add-dates-to-avoid.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/transparency-report/request:
  post:
    description: |
      Request a new transparency report either in pdf or json format and either for full or delta cases
      ...
      (mapping):
          requestType: application/vnd.sjp.request-transparency-report+json
          name: sjp.request-transparency-report
      ...
    body:
      application/vnd.sjp.request-transparency-report+json: !!null
        example:
          !include json/sjp.request-transparency-report.json
        schema:
          !include json/schema/sjp.request-transparency-report.json
    responses:
      202:
        description: Accepted

/press-transparency-report/request:
  post:
    description: |
      Request a new press transparency report either in pdf or json format and either for full or delta cases
      ...
      (mapping):
          requestType: application/vnd.sjp.request-press-transparency-report+json
          name: sjp.request-press-transparency-report
      ...
    body:
      application/vnd.sjp.request-press-transparency-report+json: !!null
        example:
          !include json/sjp.request-press-transparency-report.json
        schema:
          !include json/schema/sjp.request-press-transparency-report.json
    responses:
      202:
        description: Accepted

/cases/{caseId}/notes:
  uriParameters:
    caseId:
      description: The ID of the case to which note is added
      type: string
  post:
    description: |
      Add case note
      ...
      (mapping):
          requestType: application/vnd.sjp.add-case-note+json
          name: sjp.add-case-note
      ...
    body:
          application/vnd.sjp.add-case-note+json:
            example:
              !include json/sjp.add-case-note.json
            schema:
              !include json/schema/sjp.add-case-note.json
    responses:
      202:
        description: Accepted


/cases/{caseId}/offences-withdrawal-requests-status:
  uriParameters:
    caseId:
      description: Id of the case for which withdrawal request is made
      type: string
  post:
    description: |
      Offence withdrawal requests
      ...
      (mapping):
          requestType: application/vnd.sjp.set-offences-withdrawal-requests-status+json
          name: sjp.set-offences-withdrawal-requests-status
      ...
    body:
          application/vnd.sjp.set-offences-withdrawal-requests-status+json:
            example:
              !include json/sjp.set-offences-withdrawal-requests-status.json
            schema:
              !include json/schema/sjp.set-offences-withdrawal-requests-status.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/set-pleas:
  uriParameters:
    caseId:
      description: The ID of the case to set the pleas for
      type: string
  post:
    description: |
      Set pleas for case offences
      ...
      (mapping):
          requestType: application/vnd.sjp.set-pleas+json
          name: sjp.set-pleas
      ...
    body:
      application/vnd.sjp.set-pleas+json:
        example:
          !include json/sjp.set-pleas.json
        schema:
          !include json/schema/sjp.set-pleas.json
    responses:
          500:
            description: Internal Server Error
          202:
            description: Accepted

/cases/{caseId}/decision:
  uriParameters:
    caseId:
      description: Id of the case for which decision is made
      type: string
  post:
    description: |
      decision
      ...
      (mapping):
          requestType: application/vnd.sjp.save-decision+json
          name: sjp.save-decision
      ...
    body:
          application/vnd.sjp.save-decision+json:
            example:
              !include json/sjp.save-decision.json
            schema:
              !include json/schema/sjp.save-decision.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted

/saveAocpDecison:
  post:
    description: |
      saving aocp decision
      ...
      (mapping):
         requestType: application/vnd.sjp.expire-defendant-aocp-response-timer+json
         name: sjp.expire-defendant-aocp-response-timer
      ...
    body:
      application/vnd.sjp.expire-defendant-aocp-response-timer+json:
       example:
         !include json/sjp.expire-defendant-aocp-response-timer.json
       schema:
         !include json/schema/sjp.expire-defendant-aocp-response-timer.json
    responses:
       202:
         description: Accepted
       500:
         description: Internal Server Error


/cases/{caseId}/set-dates-to-avoid-required:
  uriParameters:
    caseId:
      description: The ID of the case to modify
      type: string
  post:
    description: |
      creates sjp.events.dates-to-avoid-required event
      ...
      (mapping):
          requestType: application/vnd.sjp.set-dates-to-avoid-required+json
          name: sjp.set-dates-to-avoid-required
      ...
    body:
      application/vnd.sjp.set-dates-to-avoid-required+json: !!null
    responses:
      202:
        description: Accepted
      500:
        description: Internal Server Error

/cases/{caseId}/resolve-case-status:
  uriParameters:
    caseId:
      description: The ID of the case to resolve
      type: string
  post:
    description: |
      creates sjp.resolve-case-status event
      ...
      (mapping):
          requestType: application/vnd.sjp.resolve-case-status+json
          name: sjp.resolve-case-status
      ...
    body:
      application/vnd.sjp.resolve-case-status+json: !!null
    responses:
      202:
        description: Accepted
      500:
        description: Internal Server Error

/cases/{caseId}/reserve-case:
  uriParameters:
    caseId:
      description: The ID of the case to reserve
      type: string
  post:
    description: |
      creates sjp.reserved-case-status event
      ...
      (mapping):
          requestType: application/vnd.sjp.reserve-case+json
          name: sjp.reserve-case
      (mapping):
          requestType: application/vnd.sjp.undo-reserve-case+json
          name: sjp.undo-reserve-case
      ...
    body:
      application/vnd.sjp.reserve-case+json: !!null
      application/vnd.sjp.undo-reserve-case+json: !!null
    responses:
      202:
        description: Accepted
      500:
        description: Internal Server Error

/cases-management-status:
  post:
    description: |
      update cases management status
      ...
      (mapping):
          requestType: application/vnd.sjp.update-cases-management-status+json
          name: sjp.update-cases-management-status
      ...
    body:
      application/vnd.sjp.update-cases-management-status+json:
        example:
          !include json/sjp.update-cases-management-status.json
        schema:
          !include json/schema/sjp.update-cases-management-status.json
    responses:
      202:
        description: Accepted
      500:
        description: Internal Server Error


/case-assignment-restriction:
  post:
    description: |
      Creates case assignment restriction
      ...
      (mapping):
          requestType: application/vnd.sjp.add-case-assignment-restriction+json
          name: sjp.add-case-assignment-restriction
      ...
    body:
      application/vnd.sjp.add-case-assignment-restriction+json:
        example:
          !include json/sjp.add-case-assignment-restriction.json
        schema:
          !include json/schema/sjp.add-case-assignment-restriction.json
    responses:
      500:
            description: Internal Server Error
      202:
        description: Accepted

/cases/{caseId}/request-delete-docs:
  uriParameters:
      caseId:
        description: The ID of the case to resolve
        type: string
  post:
    description: |
          requests deletion of docs for case.
          ...
          (mapping):
              requestType: application/vnd.sjp.request-delete-docs+json
              name: sjp.request-delete-docs
          ...
    body:
        application/vnd.sjp.request-delete-docs+json: !!null
    responses:
        202:
          description: Accepted
        500:
          description: Internal Server Error


/cases/{caseId}/applications:
  uriParameters:
    caseId:
      description: The ID of the case for the new application
      type: string
  post:
    description: |
      Create new stat decs application
      ...
      (mapping):
          requestType: application/vnd.sjp.create-case-application+json
          name: sjp.create-case-application
      ...
    body:
      application/vnd.sjp.create-case-application+json:
        example:
          !include json/sjp.create-case-application.json
        schema:
          !include json/schema/sjp.api.create-case-application.json
    responses:
          500:
            description: Internal Server Error
          202:


/cases/{caseId}/applications/{applicationId}/decision:
  uriParameters:
    caseId:
      description: Id of the case for which decision is made
      type: string
    applicationId:
      description: Id of the application belonging to the case
  post:
    description: |
      application-decision
      ...
      (mapping):
          requestType: application/vnd.sjp.save-application-decision+json
          name: sjp.save-application-decision
      ...
    body:
          application/vnd.sjp.save-application-decision+json:
            example:
              !include json/sjp.save-application-decision.json
            schema:
              !include json/schema/sjp.save-application-decision.json
    responses:
      400:
        description: Request failed validation
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}/add-financial-imposition-correlation-id:
  uriParameters:
    caseId:
      description: Id of the case containing the defendant for which the correlation/request id is added
      type: string
      required: true
    defendantId:
      description: Id of the defendant to which the correlation/request id is added
      required: true
  post:
    description: |
      Record the correlation id of the request to enforce financial impositions,
      this is later used to record the libra account number
      ...
      (mapping):
          requestType: application/vnd.sjp.add-financial-imposition-correlation-id+json
          name: sjp.add-financial-imposition-correlation-id
      ...
    body:
          application/vnd.sjp.add-financial-imposition-correlation-id+json:
            example:
              !include json/sjp.add-financial-imposition-correlation-id.json
            schema:
              !include json/schema/sjp.add-financial-imposition-correlation-id.json
    responses:
      400:
        description: Request failed validation
      202:
        description: Accepted

/cases/{caseId}/defendant/{defendantId}/add-financial-imposition-account-number-bdf:
  uriParameters:
    caseId:
      description: Id of the case containing the defendant for which the libra account number is added
      type: string
      required: true
    defendantId:
      description: Id of the defendant to which the correlation/request id is added
      required: true
  post:
    description: |
      Record the libra account number and correlation id of the request to enforce financial impositions, used by ATCM-6980 BDF only!
      ...
      (mapping):
          requestType: application/vnd.sjp.add-financial-imposition-account-number-bdf+json
          name: sjp.add-financial-imposition-account-number-bdf
      ...
    body:
          application/vnd.sjp.add-financial-imposition-account-number-bdf+json:
            example:
              !include json/sjp.add-financial-imposition-account-number-bdf.json
            schema:
              !include json/schema/sjp.add-financial-imposition-account-number-bdf.json
    responses:
      400:
        description: Request failed validation
      202:
        description: Accepted

/cases/{caseId}/documents/{documentId}/delete:
  uriParameters:
      caseId:
        description: The ID of the case to resolve
        type: string
      documentId:
        description: The ID of the document to resolve
        type: string
  post:
    description: |
      requests deletion of case documents.
      ...
      (mapping):
        requestType: application/vnd.sjp.delete-case-document+json
        name: sjp.delete-case-document
      ...
    body:
        application/vnd.sjp.delete-case-document+json:
          example:
            !include json/sjp.delete-case-document.json
          schema:
            !include json/schema/sjp.delete-case-document.json
    responses:
        202:
          description: Accepted
        500:
          description: Internal Server Error


/cases/{caseId}/complete-bdf:
  uriParameters:
    caseId:
      description: Id of the case to complete
      type: string
  post:
    description: |
      decision
      ...
      (mapping):
          requestType: application/vnd.sjp.case-complete-bdf+json
          name: sjp.case-complete-bdf
      ...
    body:
          application/vnd.sjp.case-complete-bdf+json:
            example:
              !include json/sjp.case-complete-bdf.json
            schema:
              !include json/schema/sjp.case-complete-bdf.json
    responses:
      500:
        description: Internal Server Error
      202:
        description: Accepted
