<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>uk.gov.moj.cpp.common</groupId>
        <artifactId>service-parent-pom</artifactId>
        <version>17.104.3</version>
    </parent>

    <groupId>uk.gov.moj.cpp.sjp</groupId>
    <artifactId>sjp-parent</artifactId>
    <version>17.104.192-CCT-1981-release-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec
        </sonar.jacoco.itReportPath>
        <sonar.report.export.path>sonar-report.json</sonar.report.export.path>
        <sonar.scm.provider>git</sonar.scm.provider>
        <sonar.cpd.exclusions>**/uk/gov/moj/cpp/sjp/dto/**/*,
            **/uk/gov/moj/cpp/sjp/domain/**/*,
            **/uk/gov/moj/cpp/sjp/model/**/*,
            **uk/gov/justice/core/courts/**/*,
            **/uk/gov/moj/cpp/sjp/persist/entity/**/*,
            **/uk/gov/moj/cpp/sjp/persistence/entity/**/*,
            **/uk/gov/moj/cpp/sjp/persistence/repository/**/*,
            **/uk/gov/moj/cpp/sjp/event/*.java,
            **/uk/gov/moj/cpp/sjp/event/session/**/*,
            **/uk/gov/moj/cpp/sjp/event/decision/**/*,
            **/uk/gov/moj/cpp/sjp/event/decommissioned/**/*,
            **/uk/gov/moj/cpp/sjp/event/transparency/**/*,
            **/uk/gov/moj/cpp/sjp/event/casemanagement/**/*,
            **/uk/gov/moj/cpp/sjp/repository/**/*,
            **/uk/gov/moj/cpp/sjp/query/view/response/**/*,
            **/uk/gov/moj/cpp/sjp/query/view/exception/**/*,
            **/uk/gov/moj/cpp/sjp/domain/command/CancelPlea.java,
            **/uk/gov/moj/cpp/sjp/event/AocpAcceptedEmailNotificationSent.java
        </sonar.cpd.exclusions>
        <mvn.site.url>file://${project.build.directory}/site</mvn.site.url>

        <assignment.version>6.0.0</assignment.version>
        <access-control-sjp-providers.version>4.1.4-ATCM</access-control-sjp-providers.version>
        <material.version>17.0.57</material.version>
        <notification.notify.version>17.0.1</notification.notify.version>
        <referencedata.version>17.104.137</referencedata.version>
        <referencedata.offences.version>17.104.52</referencedata.offences.version>
        <scheduling.version>17.0.11</scheduling.version>
        <authorisation.service.version>0.1.49</authorisation.service.version>
        <usersgroups.version>17.104.48</usersgroups.version>
        <progression.version>17.0.286</progression.version>
        <prosecutioncasefile.version>17.0.66</prosecutioncasefile.version>
        <access-control-sjp-providers.version>4.1.4-ATCM</access-control-sjp-providers.version>
        <cpp.framework.action.mapping.enabled>true</cpp.framework.action.mapping.enabled>
        <mvn.site.url>file://${project.build.directory}/site</mvn.site.url>
        <file.alfresco.version>2.3.0</file.alfresco.version>
        <coredomain.version>17.104.4</coredomain.version>
        <criminal-court-public-model.version>${coredomain.version}</criminal-court-public-model.version>
        <javax.el-api.version>3.0.0</javax.el-api.version>
        <joda-time.version>2.10</joda-time.version>
        <lombok.version>1.18.20</lombok.version>
        <activiti.library.version>1.3.0</activiti.library.version>
        <pojo-generation.version>1.6.0-M1</pojo-generation.version>
        <systemdocgenerator.version>17.0.96</systemdocgenerator.version>
        <document-generator-client.version>1.0.4</document-generator-client.version>
        <apache.pdfbox.version>2.0.11</apache.pdfbox.version>
        <argLine>-Djava.locale.providers=CLDR</argLine>
        <elasticsearch-maven-plugin.version>6.13</elasticsearch-maven-plugin.version>
        <elasticsearch.embedded.version>7.16.2</elasticsearch.embedded.version>
        <stagingenforcement.version>17.104.81</stagingenforcement.version>
        <unifiedsearch.version>17.0.26</unifiedsearch.version>
        <jsonassert.version>1.5.0</jsonassert.version>
        <junit4.version>4.13.1</junit4.version>
        <maven.cucumber.reporting.version>2.0.0</maven.cucumber.reporting.version>
        <jgitflow-maven-plugin.version>1.0-m5.1</jgitflow-maven-plugin.version>
        <jgitflow.maven.developBranchName>main</jgitflow.maven.developBranchName>
        <h2.version>1.4.196</h2.version>
    </properties>

    <modules>
        <module>sjp-viewstore</module>
        <module>sjp-domain</module>
        <module>sjp-event</module>
        <module>sjp-command</module>
        <module>sjp-query</module>
        <module>sjp-integration-test</module>
        <module>sjp-service</module>
        <module>sjp-json</module>
        <module>sjp-event-sources</module>
        <module>sjp-healthchecks</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <archiveClasses>true</archiveClasses>
                    <attachClasses>true</attachClasses>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.11.0.3922</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>${jvm.options}</argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>external.atlassian.jgitflow</groupId>
                <artifactId>jgitflow-maven-plugin</artifactId>
                <version>${jgitflow-maven-plugin.version}</version>
                <configuration>
                    <flowInitContext>
                        <masterBranchName>dev/release</masterBranchName>
                        <developBranchName>main</developBranchName>
                        <featureBranchPrefix>dev/feature-</featureBranchPrefix>
                        <releaseBranchPrefix>dev/release-</releaseBranchPrefix>
                        <hotfixBranchPrefix>dev/hotfix-</hotfixBranchPrefix>
                        <versionTagPrefix>v</versionTagPrefix>
                    </flowInitContext>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <enableSshAgent>true</enableSshAgent>
                    <pushReleases>true</pushReleases>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
        </dependency>
    </dependencies>

    <distributionManagement>
        <site>
            <id>site</id>
            <url>${mvn.site.url}</url>
        </site>
    </distributionManagement>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>uk.gov.moj.cpp.sjp</groupId>
                <artifactId>sjp-json</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-enveloper-provider</artifactId>
                <scope>test</scope>
                <version>${cpp.framework.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.system.documentgenerator</groupId>
                <artifactId>system-documentgenerator-client</artifactId>
                <version>${cpp.platform-libraries.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
