<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sjp-domain</artifactId>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <version>17.104.190-CCT-1981-release-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sjp-domain-transformation</artifactId>

    <packaging>pom</packaging>

    <modules>
        <module>sjp-domain-transformation-anonymise</module>
        <module>sjp-domain-transformation-postcode</module>

    </modules>

</project>
