<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sjp-event</artifactId>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <version>17.104.190-CCT-1981-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sjp-event-processor</artifactId>
    <packaging>war</packaging>

    <properties>
        <cpp.service-component>EVENT_PROCESSOR</cpp.service-component>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>

    <dependencies>
        <dependency>
            <groupId>uk.gov.moj.cpp.system.documentgenerator</groupId>
            <artifactId>system-documentgenerator-client</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.system.id-mapper</groupId>
            <artifactId>id-mapper-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${apache.pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-json</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.audit</groupId>
            <artifactId>audit-client</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>event-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice</groupId>
            <artifactId>file-alfresco</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>file-service-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>system-users-library</artifactId>
            <version>${cpp.platform-libraries.version}</version>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-cdi</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.activiti</groupId>
            <artifactId>activiti-embedded-rest</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.tinyjee.jgraphx</groupId>
                    <artifactId>jgraphx</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-domain-event-processor</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-core</artifactId>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Required by activiti engine tests -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-enveloper-provider</artifactId>
            <version>${cpp.framework.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.sjp</groupId>
                        <artifactId>sjp-command-handler</artifactId>
                        <version>${project.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.notification.notify</groupId>
                        <artifactId>notificationnotify-command-api</artifactId>
                        <version>${notification.notify.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.material</groupId>
                        <artifactId>material-command-api</artifactId>
                        <version>${material.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.systemdocgenerator</groupId>
                        <artifactId>systemdocgenerator-command-api</artifactId>
                        <version>${systemdocgenerator.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.referencedata</groupId>
                        <artifactId>referencedata-query-api</artifactId>
                        <version>${referencedata.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.prosecution.casefile</groupId>
                        <artifactId>prosecutioncasefile-query-api</artifactId>
                        <version>${prosecutioncasefile.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.usersgroups</groupId>
                        <artifactId>usersgroups-query-api</artifactId>
                        <version>${usersgroups.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.material</groupId>
                        <artifactId>material-query-api</artifactId>
                        <version>${material.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.material</groupId>
                        <artifactId>material-command-api</artifactId>
                        <version>${material.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.sjp</groupId>
                        <artifactId>sjp-query-view</artifactId>
                        <version>${project.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.scheduling</groupId>
                        <artifactId>scheduling-command-api</artifactId>
                        <version>${scheduling.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.scheduling</groupId>
                        <artifactId>scheduling-query-api</artifactId>
                        <version>${scheduling.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.assignment</groupId>
                        <artifactId>assignment-command-api</artifactId>
                        <version>${assignment.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.progression</groupId>
                        <artifactId>progression-command-api</artifactId>
                        <version>${progression.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.referencedata.offences</groupId>
                        <artifactId>referencedataoffences-query-api</artifactId>
                        <version>${referencedata.offences.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.staging.enforcement</groupId>
                        <artifactId>stagingenforcement-command-api</artifactId>
                        <version>${stagingenforcement.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.sjp</groupId>
                        <artifactId>sjp-command-api</artifactId>
                        <version>${project.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
