package uk.gov.moj.cpp.sjp.command.controller.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

rule "Command - Rule for start session"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.start-session");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for end session"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.end-session");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for update session"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.update-session-bdf");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for reset aocp session request"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.reset-aocp-session");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for assigning case"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.assign-next-case");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for assigning a case to a user"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.controller.assign-case");
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for unassigning case"
  when
    $outcome: Outcome();
    $action: Action(name == "sjp.command.unassign-case");
  then
    $outcome.setSuccess(true);
end

