<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sjp-parent</artifactId>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <version>17.104.191-CCT-1981-release-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sjp-json</artifactId>
    <packaging>jar</packaging>

    <name>sjp-json</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>common-core-domain</artifactId>
            <version>${coredomain.version}</version>
        </dependency>
       <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>sjp-public-model</artifactId>
            <version>${coredomain.version}</version>
            <scope>compile</scope>
        </dependency>
       <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>criminal-court-public-model</artifactId>
            <version>${criminal-court-public-model.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.schema</groupId>
                <artifactId>catalog-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>schema-catalog-generation</id>
                        <configuration>
                            <sourceDirectory>src/main/resources/json/schema</sourceDirectory>
                            <includes>
                                <include>**/*.json</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
