<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sjp-query</artifactId>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <version>17.104.190-CCT-1981-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sjp-query-view</artifactId>
    <packaging>war</packaging>

    <properties>
        <cpp.service-component>QUERY_VIEW</cpp.service-component>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.usersgroups</groupId>
                        <artifactId>usersgroups-query-api</artifactId>
                        <version>${usersgroups.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.referencedata.offences</groupId>
                        <artifactId>referencedataoffences-query-api</artifactId>
                        <version>${referencedata.offences.version}</version>
                        <classifier>raml</classifier>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.referencedata</groupId>
                        <artifactId>referencedata-query-api</artifactId>
                        <version>${referencedata.version}</version>
                        <classifier>raml</classifier>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.prosecution.casefile</groupId>
                        <artifactId>prosecutioncasefile-query-api</artifactId>
                        <version>${prosecutioncasefile.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.unifiedsearch.query</groupId>
                        <artifactId>unifiedsearchquery-api</artifactId>
                        <version>${unifiedsearch.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.progression</groupId>
                        <artifactId>progression-query-api</artifactId>
                        <version>${progression.version}</version>
                        <classifier>raml</classifier>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-enveloper-provider</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-json</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-domain-prosecution</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>query-view</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-rest-client</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-viewstore-persistence</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.access-control</groupId>
            <artifactId>access-control-sjp-providers</artifactId>
            <version>${cpp.platform-libraries.version}</version>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-domain-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-viewstore-persistence</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-domain-aggregate</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.access-control</groupId>
            <artifactId>access-control-common-providers</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
