<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <artifactId>sjp-viewstore</artifactId>
        <version>17.104.191-CCT-1981-release-SNAPSHOT</version>
    </parent>

    <artifactId>sjp-viewstore-liquibase</artifactId>

    <properties>
        <sonar.skip>true</sonar.skip>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>Create Event Store Schema</id>
                        <configuration>
                            <propertyFile>src/main/resources/liquibase.properties</propertyFile>
                            <contexts>${liquibase.context}</contexts>
                        </configuration>
                        <goals>
                            <goal>update</goal>
                        </goals>
                    </execution>

                </executions>

            </plugin>
        </plugins>
    </build>

</project>
