<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>sjp-domain</artifactId>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <version>17.104.191-CCT-1981-release-SNAPSHOT</version>
    </parent>

    <artifactId>sjp-domain-prosecution</artifactId>

    <name>sjp-domain-prosecution</name>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <!-- JUnit regression testing framework. -->
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-domain-common</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
