<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <parent>
      <artifactId>sjp-parent</artifactId>
      <groupId>uk.gov.moj.cpp.sjp</groupId>
      <version>17.104.191-CCT-1981-release-SNAPSHOT</version>
   </parent>
   <modelVersion>4.0.0</modelVersion>
   <artifactId>sjp-viewstore</artifactId>
   <packaging>pom</packaging>
   <modules>
      <module>sjp-viewstore-liquibase</module>
      <module>sjp-viewstore-persistence</module>
   </modules>
</project>

