<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <artifactId>sjp-parent</artifactId>
        <version>17.104.194-REL-3RD-LINE-2627-SNAPSHOT</version>
    </parent>

    <artifactId>sjp-domain</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>sjp-domain-event</module>
        <module>sjp-domain-aggregate</module>
        <module>sjp-domain-transformation</module>
        <module>sjp-domain-common</module>
        <module>sjp-domain-event-processor</module>
        <module>sjp-domain-prosecution</module>
  </modules>

</project>
