<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <artifactId>sjp-domain</artifactId>
        <version>17.104.192-CCT-1981-release-SNAPSHOT</version>
    </parent>

    <artifactId>sjp-domain-event</artifactId>

    <properties>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-domain</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.json</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.sjp</groupId>
            <artifactId>sjp-domain-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>common-core-domain</artifactId>
            <version>${coredomain.version}</version>
        </dependency>


        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.generators</groupId>
                <artifactId>pojo-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pojo-generation</id>
                        <configuration>
                            <sourceDirectory>CLASSPATH</sourceDirectory>
                            <includes>
                                <include>json/schema/fragments/gender.json</include>
                                <include>json/schema/fragments/language.json</include>
                                <include>json/schema/fragments/listing-details.json</include>
                                <include>json/schema/events/sjp.events.case-note-added.json</include>
                                <include>json/schema/events/sjp.events.case-referral-for-court-hearing-rejection-recorded.json</include>
                                <include>json/schema/events/sjp.events.case-adjourned-to-later-sjp-hearing-recorded.json</include>
                                <include>json/schema/events/sjp.events.case-adjournment-to-later-sjp-hearing-elapsed.json</include>
                                <include>json/schema/events/sjp.events.offences-withdrawal-status-set.json</include>
                                <include>json/schema/events/sjp.events.case-assignment-restriction-added.json</include>
                                <include>json/schema/commands/sjp.create-case-application.json</include>
                                <include>json/schema/commands/save-application-decision.json</include>
                                <include>json/schema/fragments/application-status.json</include>
                                <include>json/schema/fragments/result-status.json</include>
                                <include>json/schema/fragments/application-type.json</include>
                                <include>json/schema/events/sjp.events.case-application-recorded.json</include>
                                <include>json/schema/events/sjp.events.case-stat-dec-recorded.json</include>
                                <include>json/schema/events/sjp.events.case-application-for-reopening-recorded.json</include>
                                <include>json/schema/events/sjp.events.case-application-rejected.json</include>
                                <include>json/schema/fragments/application-decision-granted.json</include>
                                <include>json/schema/fragments/application-decision-rejected.json</include>
                                <include>json/schema/events/sjp.events.application-decision-saved.json</include>
                                <include>json/schema/events/sjp.events.application-decision-rejected.json</include>
                            </includes>
                            <generatorProperties implementation="uk.gov.justice.generation.pojo.core.PojoGeneratorProperties">
                                <plugins>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.typemodifying.ReferenceCustomReturnTypePlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.typemodifying.FormatCustomReturnTypePlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddToStringMethodToClassPlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddHashcodeAndEqualsPlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddEventAnnotationToClassPlugin
                                    </plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.MakeClassSerializablePlugin</plugin>
                                </plugins>
                                <typeMappings>
                                    <typeMapping>
                                        <name>uuid</name>
                                        <type>reference</type>
                                        <implementation>java.util.UUID</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>format</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date-time</name>
                                        <type>format</type>
                                        <implementation>java.time.ZonedDateTime</implementation>
                                    </typeMapping>
                                </typeMappings>
                            </generatorProperties>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.sjp</groupId>
                        <artifactId>sjp-json</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.core.domain</groupId>
                        <artifactId>common-core-domain</artifactId>
                        <version>${coredomain.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
