<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sjp-command</artifactId>
        <groupId>uk.gov.moj.cpp.sjp</groupId>
        <version>17.104.191-CCT-1981-release-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sjp-command-controller</artifactId>
    <packaging>war</packaging>
    <properties>
        <cpp.service-component>COMMAND_CONTROLLER</cpp.service-component>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.sjp</groupId>
                        <artifactId>sjp-command-handler</artifactId>
                        <version>${project.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.usersgroups</groupId>
                        <artifactId>usersgroups-query-api</artifactId>
                        <version>${usersgroups.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.sjp</groupId>
                        <artifactId>sjp-query-view</artifactId>
                        <version>${project.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.referencedata</groupId>
                        <artifactId>referencedata-query-api</artifactId>
                        <version>${referencedata.version}</version>
                        <classifier>raml</classifier>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.generators</groupId>
                <artifactId>pojo-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pojo-generation</id>
                        <configuration>
                            <skip>${skip.schema.pojo.generation}</skip>
                            <sourceDirectory>${project.basedir}/src/raml/json/schema
                            </sourceDirectory>
                            <includes>
                                <include>**/sjp.command.controller.add-case-assignment-restriction.json</include>
                            </includes>
                            <generatorProperties implementation="uk.gov.justice.generation.pojo.core.PojoGeneratorProperties">
                                <plugins>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.typemodifying.ReferenceCustomReturnTypePlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.typemodifying.FormatCustomReturnTypePlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddHashcodeAndEqualsPlugin
                                    </plugin>
                                    <plugin>
                                        uk.gov.justice.generation.pojo.plugin.classmodifying.AddToStringMethodToClassPlugin
                                    </plugin>
                                </plugins>
                                <typeMappings>
                                    <typeMapping>
                                        <name>uuid</name>
                                        <type>reference</type>
                                        <implementation>java.util.UUID</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>format</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date-time</name>
                                        <type>format</type>
                                        <implementation>java.time.ZonedDateTime</implementation>
                                    </typeMapping>
                                </typeMappings>
                            </generatorProperties>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.core.domain</groupId>
                        <artifactId>common-core-domain</artifactId>
                        <version>${coredomain.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>sjp-json</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>uk.gov.moj.cpp.audit</groupId>
            <artifactId>audit-client</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>command-controller</artifactId>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <scope>provided</scope>
        </dependency>


        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.access-control</groupId>
            <artifactId>access-control-test-utils</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.access-control</groupId>
            <artifactId>access-control-assignment-providers</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-enveloper-provider</artifactId>
            <scope>test</scope>
            <version>${cpp.framework.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>common-core-domain</artifactId>
            <version>${coredomain.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>
