#%RAML 0.8
title: API Using media type in the URL
baseUri: message://command/handler/message/sjp
version: v1

/sjp.handler.command:
  post:
    body:
      application/vnd.sjp.command.update-financial-means+json:
          schema: !include json/schema/sjp.command.update-financial-means.json
          example: !include json/sjp.command.update-financial-means.json

      application/vnd.sjp.command.delete-defendant-financial-means-information+json:
          schema: !include json/schema/sjp.command.delete-defendant-financial-means-information.json
          example: !include json/sjp.command.delete-defendant-financial-means-information.json

      application/vnd.sjp.command.update-employer+json:
          schema: !include json/schema/sjp.command.update-employer.json
          example: !include json/sjp.command.update-employer.json

      application/vnd.sjp.command.delete-employer+json:
          schema: !include json/schema/sjp.command.delete-employer.json
          example: !include json/sjp.command.delete-employer.json

      application/vnd.sjp.command.add-case-document+json:
          schema: !include json/schema/sjp.command.add-case-document.json
          example: !include json/sjp.command.add-case-document.json

      application/vnd.sjp.command.delete-case-document+json:
          schema: !include json/schema/sjp.command.delete-case-document.json
          example: !include json/sjp.command.delete-case-document.json

      application/vnd.sjp.command.upload-case-document+json:
          schema: !include json/schema/sjp.command.upload-case-document.json
          example: !include json/sjp.command.upload-case-document.json

      application/vnd.sjp.command.create-sjp-case+json:
          schema: !include json/schema/sjp.command.create-sjp-case.json
          example: !include json/sjp.command.create-sjp-case.json

      application/vnd.sjp.command.plead-online+json:
          schema: !include json/schema/sjp.command.plead-online.json
          example: !include json/sjp.command.plead-online.json

      application/vnd.sjp.command.plead-aocp-online+json:
          schema: !include json/schema/sjp.command.plead-aocp-online.json
          example: !include json/sjp.command.plead-aocp-online.json

      application/vnd.sjp.command.mark-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.mark-case-reopened-in-libra.json
        example: !include json/sjp.command.case-reopened-in-libra.json

      application/vnd.sjp.command.update-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.update-case-reopened-in-libra.json
        example: !include json/sjp.command.case-reopened-in-libra.json

      application/vnd.sjp.command.undo-case-reopened-in-libra+json:
        schema: !include json/schema/sjp.command.undo-case-reopened-in-libra.json
        example: !include json/sjp.command.undo-case-reopened-in-libra.json

      application/vnd.sjp.command.update-defendant-details+json:
        schema: !include json/schema/sjp.command.update-defendant-details.json
        example: !include json/sjp.command.update-defendant-details.json

      application/vnd.sjp.command.update-defendant-details-from-CC+json:
        schema: !include json/schema/sjp.command.update-defendant-details-from-CC.json
        example: !include json/sjp.command.update-defendant-details-from-CC.json

      application/vnd.sjp.command.update-hearing-requirements+json:
        schema: !include json/schema/sjp.command.update-hearing-requirements.json
        example: !include json/sjp.command.update-hearing-requirements.json

      application/vnd.sjp.command.update-defendant-national-insurance-number+json:
        schema: !include json/schema/sjp.command.update-defendant-national-insurance-number.json
        example: !include json/sjp.command.update-defendant-national-insurance-number.json

      application/vnd.sjp.command.start-session+json:
        schema: !include json/schema/sjp.command.start-session.json
        example: !include json/sjp.command.start-session.json

      application/vnd.sjp.command.reset-aocp-session+json: !!null

      application/vnd.sjp.command.end-session+json:
        schema: !include json/schema/sjp.command.end-session.json
        example: !include json/sjp.command.end-session.json

      application/vnd.sjp.command.update-session-bdf+json:
        schema: !include json/schema/sjp.command.update-session-bdf.json
        example: !include json/sjp.command.update-session-bdf.json

      application/vnd.sjp.command.assign-next-case+json:
        schema: !include json/schema/sjp.command.assign-next-case.json
        example: !include json/sjp.command.assign-next-case.json

      application/vnd.sjp.command.assign-case+json:
        schema: !include json/schema/sjp.command.assign-case.json
        example: !include json/sjp.command.assign-case.json

      application/vnd.sjp.command.unassign-case+json:
        schema: !include json/schema/sjp.command.unassign-case.json
        example: !include json/sjp.command.unassign-case.json

      application/vnd.sjp.command.assign-case-from-candidates-list+json:
        schema: !include json/schema/sjp.command.assign-case-from-candidates-list.json
        example: !include json/sjp.command.assign-case-from-candidates-list.json

      application/vnd.sjp.command.mark-case-ready-for-decision+json:
        schema: !include json/schema/sjp.command.mark-case-ready-for-decision.json
        example: !include json/sjp.command.mark-case-ready-for-decision.json

      application/vnd.sjp.command.unmark-case-ready-for-decision+json:
        schema: !include json/schema/sjp.command.unmark-case-ready-for-decision.json
        example: !include json/sjp.command.unmark-case-ready-for-decision.json

      application/vnd.sjp.command.add-dates-to-avoid+json:
        schema: !include json/schema/sjp.command.add-dates-to-avoid.json
        example: !include json/sjp.command.add-dates-to-avoid.json

      application/vnd.sjp.command.acknowledge-defendant-details-updates+json:
        schema: !include json/schema/sjp.command.acknowledge-defendant-details-updates.json
        example: !include json/sjp.command.acknowledge-defendant-details-updates.json

      application/vnd.sjp.command.update-case-listed-in-criminal-courts+json:
        schema: !include json/schema/sjp.command.update-case-listed-in-criminal-courts.json
        example: !include json/sjp.command.update-case-listed-in-criminal-courts.json

      application/vnd.sjp.command.record-case-referral-for-court-hearing-rejection+json:
        schema: !include json/schema/sjp.command.record-case-referral-for-court-hearing-rejection.json
        example: !include json/sjp.command.record-case-referral-for-court-hearing-rejection.json

      application/vnd.sjp.command.record-case-adjourned-to-later-sjp-hearing+json:
        example: !include json/sjp.command.record-case-adjourned-to-later-sjp-hearing.json
        schema:  !include json/schema/sjp.command.record-case-adjourned-to-later-sjp-hearing.json

      application/vnd.sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed+json:
        example: !include json/sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed.json
        schema:  !include json/schema/sjp.command.record-case-adjournment-to-later-sjp-hearing-elapsed.json

      application/vnd.sjp.command.store-transparency-report-data+json:
          schema: !include json/schema/sjp.command.store-transparency-report-data.json
          example: !include json/sjp.command.store-transparency-report-data.json

      application/vnd.sjp.command.update-transparency-report-data+json:
          schema: !include json/schema/sjp.command.update-transparency-report-data.json
          example: !include json/sjp.command.update-transparency-report-data.json

      application/vnd.sjp.command.update-press-transparency-report-data+json:
          schema: !include json/schema/sjp.command.update-press-transparency-report-data.json
          example: !include json/sjp.command.update-press-transparency-report-data.json

      application/vnd.sjp.command.store-press-transparency-report-data+json:
          schema: !include json/schema/sjp.command.store-press-transparency-report-data.json
          example: !include json/sjp.command.store-press-transparency-report-data.json

      application/vnd.sjp.command.request-transparency-report+json: !!null

      application/vnd.sjp.command.request-press-transparency-report+json: !!null

      application/vnd.sjp.command.transparency-report-failed+json:
        schema: !include json/schema/sjp.command.transparency-report-failed.json
        example: !include json/sjp.command.transparency-report-failed.json

      application/vnd.sjp.command.press-transparency-report-failed+json:
        schema: !include json/schema/sjp.command.press-transparency-report-failed.json
        example: !include json/sjp.command.press-transparency-report-failed.json

      application/vnd.sjp.command.add-case-note+json:
        example: !include json/sjp.command.add-case-note.json
        schema:  !include json/schema/sjp.command.add-case-note.json

      application/vnd.sjp.command.set-offences-withdrawal-requests-status+json:
        example: !include json/sjp.command.set-offences-withdrawal-requests-status.json
        schema:  !include json/schema/sjp.command.set-offences-withdrawal-requests-status.json

      application/vnd.sjp.command.set-pleas+json:
        example: !include json/sjp.command.set-pleas.json
        schema: !include json/schema/sjp.command.set-pleas.json

      application/vnd.sjp.command.update-all-financial-means+json:
          schema: !include json/schema/sjp.command.update-all-financial-means.json
          example: !include json/sjp.command.update-all-financial-means.json

      application/vnd.sjp.command.save-decision+json:
        example: !include json/sjp.command.save-decision.json
        schema:  !include json/schema/sjp.command.save-decision.json

      application/vnd.sjp.command.resolve-conviction-court-bdf+json:
        schema:  !include json/schema/sjp.command.resolve-conviction-court-bdf.json

      application/vnd.sjp.command.expire-defendant-response-timer+json:
        example: !include json/sjp.command.expire-defendant-response-timer.json
        schema:  !include json/schema/sjp.command.expire-defendant-response-timer.json

      application/vnd.sjp.command.expire-dates-to-avoid-timer+json:
        example: !include json/sjp.command.expire-dates-to-avoid-timer.json
        schema:  !include json/schema/sjp.command.expire-dates-to-avoid-timer.json

      application/vnd.sjp.command.expire-defendant-aocp-response-timer+json:
        example: !include json/sjp.command.expire-defendant-aocp-response-timer.json
        schema:  !include json/schema/sjp.command.expire-defendant-aocp-response-timer.json

      application/vnd.sjp.command.add-case-assignment-restriction+json:
        example: !include json/sjp.command.add-case-assignment-restriction.json
        schema:  !include json/schema/sjp.command.add-case-assignment-restriction.json

      application/vnd.sjp.command.set-dates-to-avoid-required+json: !!null

      application/vnd.sjp.command.resolve-case-status+json: !!null

      application/vnd.sjp.command.reserve-case+json: !!null

      application/vnd.sjp.command.undo-reserve-case+json: !!null

      application/vnd.sjp.command.update-cases-management-status+json:
        example: !include json/sjp.command.update-cases-management-status.json
        schema:  !include json/schema/sjp.command.update-cases-management-status.json

      application/vnd.sjp.command.change-case-management-status+json:
       example: !include json/sjp.command.change-case-management-status.json
       schema:  !include json/schema/sjp.command.change-case-management-status.json

      application/vnd.sjp.command.request-delete-docs+json:
        example: !include json/sjp.command.request-delete-docs.json
        schema: !include json/schema/sjp.command.request-delete-docs.json

      application/vnd.sjp.command.handler.create-case-application+json:
         example: !include json/sjp.command.handler.create-case-application.json
         schema: !include json/schema/sjp.command.handler.create-case-application.json

      application/vnd.sjp.command.handler.save-application-decision+json:
          example: !include json/sjp.command.handler.save-application-decision.json
          schema: !include json/schema/sjp.command.handler.save-application-decision.json

      application/vnd.sjp.command.record-granted-application-results+json:
        example: !include json/sjp.command.record-granted-application-results.json
        schema: !include json/schema/sjp.command.record-granted-application-results.json

      application/vnd.sjp.command.save-application-offences-results+json:
        example: !include json/sjp.command.save-application-offences-results.json
        schema: !include json/schema/sjp.command.save-application-offences-results.json

      application/vnd.sjp.command.add-financial-imposition-correlation-id+json:
          example: !include json/sjp.command.add-financial-imposition-correlation-id.json
          schema: !include json/schema/sjp.command.add-financial-imposition-correlation-id.json

      application/vnd.sjp.command.add-financial-imposition-account-number+json:
          example: !include json/sjp.command.add-financial-imposition-account-number.json
          schema: !include json/schema/sjp.command.add-financial-imposition-account-number.json

      application/vnd.sjp.command.add-financial-imposition-account-number-bdf+json:
          example: !include json/sjp.command.add-financial-imposition-account-number-bdf.json
          schema: !include json/schema/sjp.command.add-financial-imposition-account-number-bdf.json

      application/vnd.sjp.command.endorsement-removal-notification-generated+json:
          schema: !include json/schema/sjp.command.endorsement-removal-notification-generated.json
          example: !include json/sjp.command.endorsement-removal-notification-generated.json

      application/vnd.sjp.command.endorsement-removal-notification-generation-failed+json:
          schema: !include json/schema/sjp.command.endorsement-removal-notification-generation-failed.json
          example: !include json/sjp.command.endorsement-removal-notification-generation-failed.json

      application/vnd.sjp.command.endorsement-removal-notification-queued+json:
          schema: !include json/schema/sjp.command.endorsement-removal-notification-queued.json
          example: !include json/sjp.command.endorsement-removal-notification-queued.json

      application/vnd.sjp.command.endorsement-removal-notification-failed+json:
          schema: !include json/schema/sjp.command.endorsement-removal-notification-failed.json
          example: !include json/sjp.command.endorsement-removal-notification-failed.json

      application/vnd.sjp.command.endorsement-removal-notification-sent+json:
          schema: !include json/schema/sjp.command.endorsement-removal-notification-sent.json
          example: !include json/sjp.command.endorsement-removal-notification-sent.json

      application/vnd.sjp.command.update-partial-aocp-criteria-notification-to-prosecutor-status+json:
          schema: !include json/schema/sjp.command.update-partial-aocp-criteria-notification-to-prosecutor-status.json
          example: !include json/sjp.command.update-partial-aocp-criteria-notification-to-prosecutor-status.json

      application/vnd.sjp.command.enforcement-pending-application-check-requires-notification+json:
          schema: !include json/schema/sjp.command.enforcement-pending-application-check-requires-notification.json
          example: !include json/sjp.command.enforcement-pending-application-check-requires-notification.json

      application/vnd.sjp.command.enforcement-pending-application-generate-notification+json:
          schema: !include json/schema/sjp.command.enforcement-pending-application-generate-notification.json
          example: !include json/sjp.command.enforcement-pending-application-generate-notification.json

      application/vnd.sjp.command.enforcement-pending-application-fail-generation-notification+json:
          schema: !include json/schema/sjp.command.enforcement-pending-application-fail-generation-notification.json
          example: !include json/sjp.command.enforcement-pending-application-fail-generation-notification.json

      application/vnd.sjp.command.enforcement-pending-application-queue-notification+json:
          schema: !include json/schema/sjp.command.enforcement-pending-application-queue-notification.json
          example: !include json/sjp.command.enforcement-pending-application-queue-notification.json

      application/vnd.sjp.command.enforcement-pending-application-fail-notification+json:
          schema: !include json/schema/sjp.command.enforcement-pending-application-fail-notification.json
          example: !include json/sjp.command.enforcement-pending-application-fail-notification.json

      application/vnd.sjp.command.enforcement-pending-application-send-notification+json:
          schema: !include json/schema/sjp.command.enforcement-pending-application-send-notification.json
          example: !include json/sjp.command.enforcement-pending-application-send-notification.json

      application/vnd.sjp.command.update-aocp-acceptance-email-notification+json:
          schema: !include json/schema/sjp.command.update-aocp-acceptance-email-notification.json
          example: !include json/sjp.command.update-aocp-acceptance-email-notification.json

      application/vnd.sjp.command.update-cc-case-application-status+json:
          schema: !include json/schema/sjp.command.update-cc-case-application-status.json
          example: !include json/sjp.command.update-cc-case-application-status.json

      application/vnd.sjp.command.resubmit-results+json:
          schema: !include json/schema/sjp.command.resubmit-results.json

      application/vnd.sjp.command.mark-as-legal-soc-checked+json:
          schema: !include json/schema/sjp.command.mark-as-legal-soc-checked.json

      application/vnd.sjp.command.plead-online-pcq-visited+json:
        schema: !include json/schema/sjp.command.plead-online-pcq-visited.json
        example: !include json/sjp.command.plead-online-pcq-visited.json

      application/vnd.sjp.command.resolve-case-aocp-eligibility+json:
        schema: !include json/schema/sjp.command.resolve-case-aocp-eligibility.json

      application/vnd.sjp.command.accept-pending-defendant-changes+json:
        example: !include json/sjp.command.accept-pending-defendant-changes.json
        schema: !include json/schema/sjp.command.accept-pending-defendant-changes.json

      application/vnd.sjp.command.accept-pending-defendant-changes-from-CC+json:
        example: !include json/sjp.command.accept-pending-defendant-changes.json
        schema: !include json/schema/sjp.command.accept-pending-defendant-changes.json

      application/vnd.sjp.command.reject-pending-defendant-changes+json:
        example: !include json/sjp.command.reject-pending-defendant-changes.json
        schema: !include json/schema/sjp.command.reject-pending-defendant-changes.json

      application/vnd.sjp.command.update-case-listed-in-cc+json:
        schema: !include json/schema/sjp.command.update-case-listed-in-cc.json
        example: !include json/sjp.command.update-case-listed-in-cc.json

      application/vnd.sjp.command.update-offence-code+json:
        schema: !include json/schema/sjp.command.update-offence-code.json

      application/vnd.sjp.command.case-complete-bdf+json:
        schema: !include json/schema/sjp.command.case-complete-bdf.json
